<footer>
	<!--Icons used from https://www.vecteezy.com/vector-art/95039-free-social-media-icons-->
	<a href="https://www.youtube.com" class="socialmedia">
	<img src="images/Youtube.png" alt="youtube link" width="20"/></a>
	<a href="https://www.twitter.com" class="socialmedia"><img src="images/Twitter.png" alt="twitter link" width="20"/></a>
	<a href="https://www.fb.com" class="socialmedia"><img src="images/Facebook.png" alt="Facebook Link" width="20"/></a>
		<div id="contact">
	<p id="contacth"><strong>Contact us:</strong></p>
	<p>Phone No: (04)98888785<br/>
	  Address: 607 Canterbury Rd<br/>
	  Surrey Hills VIC 3127	<br/>
	Email: <a id="ContactEmail" href="mailto:103076376@student.swin.edu.au?Subject=Enquires%20about%20website" >103076376@student.swin.edu.au</a></p>
	</div>
	<div>
	<h3>About us</h3>
	<a href="product.php" class="footer">Membership information</a>
	<a href="about.php" class="footer">About the developer</a>
	<a href="equire.php" class="footer">Contact Us</a>
	<a href="enhancement.php" class="footer">Enhancement on the website</a>
	</div>

	
  <p>Copyright &copy; Active Fitness All rights reserved</p>
</footer>