	<nav>
		<a href="product.php">About Active</a>
		<a href="equire.php">Contact Us</a>
		<a href="manager.php">Management</a>
  <div class="dropdown">
    <button class="dropbtn">Enhancement
    </button>
    <div class="dropdown-content">
      <a href="enhancement.php">Enhancement1</a>
      <a href="enhancement2.php">Enhancement2</a>
	  <a href="enhancement3.php">Enhancement3</a>
    </div>
  </div>
	  </nav>
